services:
  audioMetadataGeniusBackend:
    container_name: audioMetadataGeniusBackend
    networks:
      - audioMetadataGeniusNetwork
    image: node:22-bullseye-slim
    volumes:
      - ./backend:/app
      - "${MUSIC_DIR}:/music"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    working_dir: /app
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/audio_metadata_genius
    command: sh -c "npm install -g nodemon && npm install --verbose && npm run dev && sleep infinity"

  mongo:
    container_name: audioMetadataGeniusMongo
    image: mongo:7.0
    restart: unless-stopped
    networks:
      - audioMetadataGeniusNetwork
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  audioMetadataGeniusNetwork:
    driver: bridge

volumes:
  mongo-data:
