services:
  audioMetadataGeniusBackend:
    container_name: audioMetadataGeniusBackend
    networks:
      - audioMetadataGeniusNetwork
    image: node:22-bullseye-slim
    volumes:
      - ./backend:/app
      - "${MUSIC_DIR}:/app/music"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    working_dir: /app
    env_file:
      - .env
    command: sh -c "npm install -g nodemon && npm install --verbose && npm run dev && sleep infinity"

networks:
  audioMetadataGeniusNetwork:
    driver: bridge
